### ISSUE TITLE
Not functioning

### ISSUE THREAD

**Issue by TheRonGDD** [HydraheadHunter/Data-Driven-Stacks#6]
Using version Data-Driven-Stack-Sizes 0.8.5-1.21

Items max_stack_size is unchanged regardless of in inventory or in container or on ground or newly crafted.

Not sure what to do with this. 
1. Created a datapack max_stack_size and put this in the world\datapacks directory. 
2. Created pack.mcmeta in max_stack_size with the contents 
{
  "pack": {
    "pack_format": 48,
    "description": "Change Max Stack Size"
  }
}
3. Created a folder structure data_stacks\tags\items inside max_stack_size
4. Created a file max_stack_size_16.json inside items with the contents 
{
"values": [
"minecraft:totem_of_undying",
"minecraft:lingering_potion",
"minecraft:potion",
"minecraft:splash_potion"
]
}
5. Created a file inside items max_stack_size_64.json with the contents
{
"values": [
"minecraft:egg",
"minecraft:lava_bucket",
"minecraft:water_bucket",
"minecraft:enchanted_book"
"minecraft:beetroot_soup",
"minecraft:enchanted_book",
"minecraft:rabbit_stew",
"minecraft:suspicious_stew",
"minecraft:honey_bottle",
"minecraft:saddle",
"minecraft:ender_pearl",
"minecraft:bucket",
"minecraft:lava_bucket"
"minecraft:water_bucket",
"minecraft:milk_bucket",
"minecraft:powder_snow_bucket"
]
}

**Comment by TheRonGDD** [comment]
mod seems to cause tps issues also.

data-stacks (v0.8.5-1.21)
Server thread974.07%
net.minecraft.item.ItemStack.handler$zik000$data-stacks$updateMaxStackSizeWithTag()974.00%
net.minecraft.item.ItemStack.findEntry()968.43%
java.util.stream.ReferencePipeline.toList()968.36%
java.util.stream.ReferencePipeline.toArray()968.28%
java.util.stream.ReferencePipeline.toArray()968.28%
java.util.stream.AbstractPipeline.evaluateToArrayNode()968.19%
java.util.stream.AbstractPipeline.evaluate()1052.04%
java.util.stream.AbstractPipeline.wrapAndCopyInto()1048.85%
java.util.stream.AbstractPipeline.copyInto()1048.28%
java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining()1042.94%

**Comment by G93d14** [comment]
I was just about to post an issue for these two complaints myself.

I have also tried using the minecraft datapack format for tags, and renaming the namespace to data-stacks. My folder structure is in the correct (for datapacks) structure, being /data/data_stacks/tags/item/

**Comment by HydraheadHunter** [comment]
I think I've identifed a probable cause for the tps issue, which I'll implementing a optimistic fix for in my next patch ~whenever that is~ hopefully soon. If that doesn't do the trick wrt tps, it'll take someone cleverer than me to figure out, or me but with more time on my hands.

As for what's causing your datapack to not work, without access to the exact datapack it'll be difficult for me to figure anything out beyond, "items" should be "item", and that doesn't help the other person who says theyr using "item" already." 

I've just uploaded a functional 'example pack' of what I plan to use in my world to modrinth, which works on my machine, but as that'll take time to get through modrinth moderation, I'll be committing the pack as a zip in main/assets/examples too for your immediate convience. 

And while writing this up I think I've figured out the problem... standby. Nope, that wasn't the cause, back to that commiting a folder.

**Comment by TheRonGDD** [comment]
Just to add a bit more of what I am seeing on my server when running the mod. Not sure if this is helpful. Removing the mod brings the hopper helper back down to normal.

lithium (v0.12.7)
Server thread778.15%
net.minecraft.block.entity.HopperBlockEntity.handler$bed000$lithium$lithiumExtract()767.46%
me.jellysquid.mods.lithium.common.hopper.HopperHelper.tryMoveSingleItem()495.96%
me.jellysquid.mods.lithium.common.hopper.HopperHelper.tryMoveSingleItem()551.05%
net.minecraft.item.ItemStack.getMaxCount()550.99%
net.minecraft.item.ItemStack.handler$zik000$data-stacks$updateMaxStackSizeWithTag()604.97%
net.minecraft.item.ItemStack.findEntry()600.69%
java.util.stream.ReferencePipeline.toList()600.69%
java.util.stream.ReferencePipeline.toArray()600.69%
java.util.stream.ReferencePipeline.toArray()600.69%
java.util.stream.AbstractPipeline.evaluateToArrayNode()600.69%
java.util.stream.AbstractPipeline.evaluate()655.17%
java.util.stream.AbstractPipeline.wrapAndCopyInto()653.28%
java.util.stream.AbstractPipeline.copyInto()652.83%
java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining()649.84%
java.util.HashMap$EntrySpliterator.forEachRemaining()658.09%
java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$$Lambda/0x000001c24cd78f68.accept()550.75%
java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0()550.75%785760ms (self: 720ms - 0.50%)
java.util.stream.ReferencePipeline$2$1.accept()550.25%
net.minecraft.item.ItemStack$$Lambda/0x000001c24cf16b78.test()241.56%
net.minecraft.item.ItemStack.md8f1dda$data-stacks$lambda$findEntry$0$0()241.56%
net.minecraft.item.ItemStack.itemIsIn()241.56%
net.minecraft.item.ItemStack.isIn()241.56%
net.minecraft.registry.entry.RegistryEntry$Reference.isIn()241.56%
java.util.ImmutableCollections$Set12.contains()241.56%

**Comment by HydraheadHunter** [comment]
No, yeah, that information makes a lot of sense... as a seporate thing to look into from what I was concerned about causing tps lag.

The commit of my version of a (for me) working datapack is in: on example_pack.

If you'd be willing to check if it works for you, that'd be appreciated.

**Comment by HydraheadHunter** [comment]
Whell, this is embarassing: despite, I thought, not doing anything on the client side of things, the mod is needeseems to be required client-side to run properly on a server. 

I'll update the modrinth page to reflect this, as I imagine that's what's causing y'alls' issue with loading the packs: and I'll add divorcing the client to my list of problems.

Sorry for the disappointment and inconvience.

**Comment by TheRonGDD** [comment]
Adjusting namespace to match the example you provided made the mod functional. 
For me this was "\datapacks\max_stack_size\data\data_stacks\tags\item" vs "\datapacks\max_stack_size\data_stacks\tags\items".

The "not functioning at all" issue was due to outdated documentation and/or user error.

I am still seeing tps issues.

**Comment by TheRonGDD** [comment]
[max_stack_size.zip](https://github.com/user-attachments/files/16284756/max_stack_size.zip)

My functional datapack.

**Comment by HydraheadHunter** [comment]
Okay: I'm gonna mark this issue as resolved. I've opened a seporate issue for the TPS and for the mod not functioning server-side without client-side support.

Rest assured, I'm looking into both.

**Comment by G93d14** [comment]
[stack_to_256.zip](https://github.com/user-attachments/files/16285726/stack_to_256.zip)
Here is my datapack, just in case i do have something wrong with it that makes it not work. I am launching this instance through prism launcher, though that shouldn't affect things

**Comment by TheRonGDD** [comment]
Looks like there are issues in your datapack.

[12:04:47] [Worker-Main-15/ERROR]: Couldn't load tag data-stacks:max_stack_size_32 as it is missing following references: minecraft:pitcher_pod_seeds (from file/stack_to_256)
[12:04:47] [Worker-Main-15/ERROR]: Couldn't load tag data-stacks:entity/villagers_stack_less as it is missing following references: minecraft:pitcher_pod_seeds (from file/stack_to_256)
[12:04:47] [Worker-Main-15/ERROR]: Couldn't load tag data-stacks:max_stack_size_256 as it is missing following references: minecraft:azalea_bush (from file/stack_to_256), minecraft:bamboo_sapling (from file/stack_to_256), minecraft:waxed_exposed_weathered_copper_bulb (from file/stack_to_256), minecraft:waxed_exposed_weathered_copper_door (from file/stack_to_256), minecraft:waxed_exposed_weathered_copper_trapdoor (from file/stack_to_256), minecraft:waxed_exposed_weathered_copper_grate (from file/stack_to_256), minecraft:flowering_azalea_bush (from file/stack_to_256), minecraft:grass (from file/stack_to_256), minecraft:powder_snow_cauldron (from file/stack_to_256), minecraft:scute (from file/stack_to_256), minecraft:wall_torch (from file/stack_to_256)

**Comment by G93d14** [comment]
ah. how did I never notice that in the log?

thank you for taking the time to check my silly mistake. must have added
that on accident when I was making my superlist of all obtainable items in
the game.
