### ISSUE TITLE
Mod intended to be Server-Side only. Does not function without Client-Side Copy.

### ISSUE THREAD

**Issue by HydraheadHunter** [HydraheadHunter/Data-Driven-Stacks#7]
Seporating this into an individual issue from the initial issue raising it: The server-side mod doesn't have full functionality without client-side support.

I'm unsure of the cause.

**Comment by TheRonGDD** [comment]
Not sure who reported this, but I would be happy to test their configuration. I have no issues running this server side only. It might be a config issue as I did experience that.

**Comment by HydraheadHunter** [comment]
Might just be my magic touch (derogatory) making it not work for me without also being client-side. 

I ran into this issue initially looking into your issue: running the mod on an out-of-the-box fabric server (mc1.21 - loader 0.15.11) with nothing but the fabric api (0.100.4 for 1.21), intially without the mod installed on my client. To see if your issue was more than just `item` instead of `items`.

I've tried both the 0.8.5 example pack and the newer 0.9.0 example pack.

**Comment by HydraheadHunter** [comment]
Might be an idiot. Fabric api 100.4 compiles, but my mod's dependancies are listed as 100.6+: might be what's causing my troubles...

It was not. Still might be an idiot, but that's unrelated.

**Comment by venaminecraft** [comment]
> Seporating this into an individual issue from the initial issue raising it: The server-side mod doesn't have full functionality without client-side support.
> 
> I'm unsure of the cause.

Any update on this? 🤔

**Comment by HydraheadHunter** [comment]
Well, I still have no idea about what the cause was, but survival gameplay seems to be working correctly as of 0.9.5, so I'mma move things back to serverside and keep an eye on it.

**Comment by venaminecraft** [comment]
Great to hear 😄 
I have another question: What happens if the mod gets removed, do stack gets counted down to x64 (if it was at least x65)?
No harm to the world?

**Comment by HydraheadHunter** [comment]
There'd be no harm to the world as long as no stacks exist with a max stack size over 99.

Part of minecraft stack validation is checking the `max_stack_size` item component against the 'max stack size cap' which is 99. If a stack is declared invalid (as it would do if it found a x100 stack of dirt without the mod installed), minecraft throws a hissy abouts it, and that hissy crashes the world.

If you don't have any x100+ stacks in the world, you're perfectly safe to uninstall.

But if you do have any, you'll need to find every stack that's too large and get both them and their `max_stack_size component down to at most `99` to safely uninstall.
