### ISSUE TITLE
Mod is not decreasing max stack size outside of moddev environment.

### ISSUE THREAD

**Issue by HydraheadHunter** [HydraheadHunter/Data-Driven-Stacks#9]
Data Driven Stacks is supposed to be able to override stack size going both up and down. 

This functionally works in my dev-environment, but when using the jar in an actually instance of minecraft (fabric loader), the mod is only capable of increasing max stack size.

EG:
A `max_stack_size_16.json` containing `{ "values":[ "minecraft:golden_apple", "minecraft:white_bed" ] }` correctly decreases  MMS for  golden apples and increases MMS white beds, both to the value of 16 in my development environment, but running minecraft with the .jar and the same datapack installed only increases MSS for white beds while golden apples continue to stack to 64.

**Comment by HydraheadHunter** [comment]
The source of the problem has been identified as an incompatability issue with the [Sakura-Ryoko fork of tweakeroo](https://github.com/sakura-ryoko/tweakeroo), which overrides `ItemStack#getMaxCount()`'s return value with 

 ```
Math.max( 
this.getComponents().getOrDefault(DataComponentTypes.MAX_STACK_SIZE, 1), 
( (IItemStackLimit)this.getItem() ).getMaxStackSize( (ItemStack)(Object)this) )
;
```` 

Naturally, `Math.max. results in the larger stack sizes functioning fine, but the smaller stack sizes being overriden with their item's default values. 

Will request a compatability change, but is not my mod causing this problem.

**Comment by sakura-ryoko** [comment]
Update your Tweakeroo.
